#!/bin/bash

# ==========================================
# DevOps Auto Installer - Configuration
# ==========================================

# ==========================================
# Kubernetes
# ==========================================

KUBERNETES_MINOR_VERSION="1.36"

# Kubernetes Pod Network
POD_CIDR="192.168.0.0/16"

# ==========================================
# Calico
# ==========================================

CALICO_VERSION="3.31.2"

# ==========================================
# Jenkins
# ==========================================

JENKINS_PORT="8080"

# ==========================================
# Prometheus
# ==========================================

PROMETHEUS_PORT="9090"

# ==========================================
# Grafana
# ==========================================

GRAFANA_PORT="3000"